// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package query

import (
	"context"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agent (id, capability_id, name, role, model_hint, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, capability_id, name, role, model_hint, created_at, updated_at
`

type CreateAgentParams struct {
	ID           string `json:"id"`
	CapabilityID string `json:"capability_id"`
	Name         string `json:"name"`
	Role         string `json:"role"`
	ModelHint    string `json:"model_hint"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, createAgent,
		arg.ID,
		arg.CapabilityID,
		arg.Name,
		arg.Role,
		arg.ModelHint,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.CapabilityID,
		&i.Name,
		&i.Role,
		&i.ModelHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgent = `-- name: GetAgent :one
SELECT id, capability_id, name, role, model_hint, created_at, updated_at FROM agent WHERE id = ?
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.CapabilityID,
		&i.Name,
		&i.Role,
		&i.ModelHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentByRole = `-- name: GetAgentByRole :one
SELECT a.id, a.capability_id, a.name, a.role, a.model_hint, a.created_at, a.updated_at
FROM agent a
JOIN capability c ON c.id = a.capability_id
WHERE c.company_id = ? AND a.role = ?
ORDER BY a.created_at
LIMIT 1
`

type GetAgentByRoleParams struct {
	CompanyID string `json:"company_id"`
	Role      string `json:"role"`
}

func (q *Queries) GetAgentByRole(ctx context.Context, arg GetAgentByRoleParams) (Agent, error) {
	row := q.db.QueryRowContext(ctx, getAgentByRole, arg.CompanyID, arg.Role)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.CapabilityID,
		&i.Name,
		&i.Role,
		&i.ModelHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentsByCapability = `-- name: ListAgentsByCapability :many
SELECT id, capability_id, name, role, model_hint, created_at, updated_at FROM agent WHERE capability_id = ? ORDER BY name
`

func (q *Queries) ListAgentsByCapability(ctx context.Context, capabilityID string) ([]Agent, error) {
	rows, err := q.db.QueryContext(ctx, listAgentsByCapability, capabilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.CapabilityID,
			&i.Name,
			&i.Role,
			&i.ModelHint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
