// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: approval.sql

package query

import (
	"context"
	"database/sql"
)

const createApproval = `-- name: CreateApproval :one
INSERT INTO approval (id, task_id, risk, reason, status, requested_by, created_at)
VALUES (?, ?, ?, ?, 'pending', ?, ?)
RETURNING id, task_id, risk, reason, status, requested_by, decided_by, decision_note, created_at, decided_at
`

type CreateApprovalParams struct {
	ID          string `json:"id"`
	TaskID      string `json:"task_id"`
	Risk        string `json:"risk"`
	Reason      string `json:"reason"`
	RequestedBy string `json:"requested_by"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRowContext(ctx, createApproval,
		arg.ID,
		arg.TaskID,
		arg.Risk,
		arg.Reason,
		arg.RequestedBy,
		arg.CreatedAt,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Risk,
		&i.Reason,
		&i.Status,
		&i.RequestedBy,
		&i.DecidedBy,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getApproval = `-- name: GetApproval :one
SELECT id, task_id, risk, reason, status, requested_by, decided_by, decision_note, created_at, decided_at FROM approval WHERE id = ?
`

func (q *Queries) GetApproval(ctx context.Context, id string) (Approval, error) {
	row := q.db.QueryRowContext(ctx, getApproval, id)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Risk,
		&i.Reason,
		&i.Status,
		&i.RequestedBy,
		&i.DecidedBy,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const hasApprovedApproval = `-- name: HasApprovedApproval :one
SELECT COUNT(*) FROM approval WHERE task_id = ? AND status = 'approved'
`

func (q *Queries) HasApprovedApproval(ctx context.Context, taskID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasApprovedApproval, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listApprovals = `-- name: ListApprovals :many
SELECT id, task_id, risk, reason, status, requested_by, decided_by, decision_note, created_at, decided_at FROM approval
WHERE (?1 = '' OR status = ?2)
ORDER BY created_at
`

type ListApprovalsParams struct {
	StatusFilter interface{} `json:"status_filter"`
	Status       string      `json:"status"`
}

func (q *Queries) ListApprovals(ctx context.Context, arg ListApprovalsParams) ([]Approval, error) {
	rows, err := q.db.QueryContext(ctx, listApprovals, arg.StatusFilter, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Risk,
			&i.Reason,
			&i.Status,
			&i.RequestedBy,
			&i.DecidedBy,
			&i.DecisionNote,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApproval = `-- name: UpdateApproval :one
UPDATE approval
SET status = ?, decided_by = ?, decision_note = ?, decided_at = ?
WHERE id = ?
RETURNING id, task_id, risk, reason, status, requested_by, decided_by, decision_note, created_at, decided_at
`

type UpdateApprovalParams struct {
	Status       string        `json:"status"`
	DecidedBy    string        `json:"decided_by"`
	DecisionNote string        `json:"decision_note"`
	DecidedAt    sql.NullInt64 `json:"decided_at"`
	ID           string        `json:"id"`
}

func (q *Queries) UpdateApproval(ctx context.Context, arg UpdateApprovalParams) (Approval, error) {
	row := q.db.QueryRowContext(ctx, updateApproval,
		arg.Status,
		arg.DecidedBy,
		arg.DecisionNote,
		arg.DecidedAt,
		arg.ID,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Risk,
		&i.Reason,
		&i.Status,
		&i.RequestedBy,
		&i.DecidedBy,
		&i.DecisionNote,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}
