// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package query

import (
	"context"
)

const createAudit = `-- name: CreateAudit :one
INSERT INTO audit (id, entity_type, entity_id, action, actor, detail, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, entity_type, entity_id, "action", actor, detail, created_at
`

type CreateAuditParams struct {
	ID         string `json:"id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Action     string `json:"action"`
	Actor      string `json:"actor"`
	Detail     string `json:"detail"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) CreateAudit(ctx context.Context, arg CreateAuditParams) (Audit, error) {
	row := q.db.QueryRowContext(ctx, createAudit,
		arg.ID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Actor,
		arg.Detail,
		arg.CreatedAt,
	)
	var i Audit
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Actor,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const listAudits = `-- name: ListAudits :many
SELECT id, entity_type, entity_id, "action", actor, detail, created_at FROM audit
WHERE (?1 = '' OR entity_type = ?2)
ORDER BY created_at DESC
`

type ListAuditsParams struct {
	EntityTypeFilter interface{} `json:"entity_type_filter"`
	EntityType       string      `json:"entity_type"`
}

func (q *Queries) ListAudits(ctx context.Context, arg ListAuditsParams) ([]Audit, error) {
	rows, err := q.db.QueryContext(ctx, listAudits, arg.EntityTypeFilter, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Audit{}
	for rows.Next() {
		var i Audit
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Actor,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
