// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capability.sql

package query

import (
	"context"
)

const createCapability = `-- name: CreateCapability :one
INSERT INTO capability (id, company_id, code, name, description, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, company_id, code, name, description, created_at, updated_at
`

type CreateCapabilityParams struct {
	ID          string `json:"id"`
	CompanyID   string `json:"company_id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) CreateCapability(ctx context.Context, arg CreateCapabilityParams) (Capability, error) {
	row := q.db.QueryRowContext(ctx, createCapability,
		arg.ID,
		arg.CompanyID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCapability = `-- name: GetCapability :one
SELECT id, company_id, code, name, description, created_at, updated_at FROM capability WHERE id = ?
`

func (q *Queries) GetCapability(ctx context.Context, id string) (Capability, error) {
	row := q.db.QueryRowContext(ctx, getCapability, id)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCapabilityByCode = `-- name: GetCapabilityByCode :one
SELECT id, company_id, code, name, description, created_at, updated_at FROM capability WHERE company_id = ? AND code = ?
`

type GetCapabilityByCodeParams struct {
	CompanyID string `json:"company_id"`
	Code      string `json:"code"`
}

func (q *Queries) GetCapabilityByCode(ctx context.Context, arg GetCapabilityByCodeParams) (Capability, error) {
	row := q.db.QueryRowContext(ctx, getCapabilityByCode, arg.CompanyID, arg.Code)
	var i Capability
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCapabilitiesByCompany = `-- name: ListCapabilitiesByCompany :many
SELECT id, company_id, code, name, description, created_at, updated_at FROM capability WHERE company_id = ? ORDER BY code
`

func (q *Queries) ListCapabilitiesByCompany(ctx context.Context, companyID string) ([]Capability, error) {
	rows, err := q.db.QueryContext(ctx, listCapabilitiesByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Capability{}
	for rows.Next() {
		var i Capability
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
