// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decision.sql

package query

import (
	"context"
)

const createDecision = `-- name: CreateDecision :one
INSERT INTO decision (id, company_id, title, kind, status, body, decided_by, source, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, company_id, title, kind, status, body, decided_by, source, created_at, updated_at
`

type CreateDecisionParams struct {
	ID        string `json:"id"`
	CompanyID string `json:"company_id"`
	Title     string `json:"title"`
	Kind      string `json:"kind"`
	Status    string `json:"status"`
	Body      string `json:"body"`
	DecidedBy string `json:"decided_by"`
	Source    string `json:"source"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error) {
	row := q.db.QueryRowContext(ctx, createDecision,
		arg.ID,
		arg.CompanyID,
		arg.Title,
		arg.Kind,
		arg.Status,
		arg.Body,
		arg.DecidedBy,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Kind,
		&i.Status,
		&i.Body,
		&i.DecidedBy,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDecision = `-- name: GetDecision :one
SELECT id, company_id, title, kind, status, body, decided_by, source, created_at, updated_at FROM decision WHERE id = ?
`

func (q *Queries) GetDecision(ctx context.Context, id string) (Decision, error) {
	row := q.db.QueryRowContext(ctx, getDecision, id)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Kind,
		&i.Status,
		&i.Body,
		&i.DecidedBy,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDecisions = `-- name: ListDecisions :many
SELECT id, company_id, title, kind, status, body, decided_by, source, created_at, updated_at FROM decision
WHERE (?1 = '' OR company_id = ?2)
  AND (?3 = '' OR kind = ?4)
ORDER BY created_at DESC
`

type ListDecisionsParams struct {
	CompanyFilter interface{} `json:"company_filter"`
	CompanyID     string      `json:"company_id"`
	KindFilter    interface{} `json:"kind_filter"`
	Kind          string      `json:"kind"`
}

func (q *Queries) ListDecisions(ctx context.Context, arg ListDecisionsParams) ([]Decision, error) {
	rows, err := q.db.QueryContext(ctx, listDecisions,
		arg.CompanyFilter,
		arg.CompanyID,
		arg.KindFilter,
		arg.Kind,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Decision{}
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Kind,
			&i.Status,
			&i.Body,
			&i.DecidedBy,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
