// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: endpoint.sql

package query

import (
	"context"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoint (id, company_id, name, base_url, token_enc, proto, vendor, selected_model, role, status, models_cache, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, company_id, name, base_url, token_enc, proto, vendor, selected_model, role, status, models_cache, created_at, updated_at
`

type CreateEndpointParams struct {
	ID            string `json:"id"`
	CompanyID     string `json:"company_id"`
	Name          string `json:"name"`
	BaseUrl       string `json:"base_url"`
	TokenEnc      string `json:"token_enc"`
	Proto         string `json:"proto"`
	Vendor        string `json:"vendor"`
	SelectedModel string `json:"selected_model"`
	Role          string `json:"role"`
	Status        string `json:"status"`
	ModelsCache   string `json:"models_cache"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRowContext(ctx, createEndpoint,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.BaseUrl,
		arg.TokenEnc,
		arg.Proto,
		arg.Vendor,
		arg.SelectedModel,
		arg.Role,
		arg.Status,
		arg.ModelsCache,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.BaseUrl,
		&i.TokenEnc,
		&i.Proto,
		&i.Vendor,
		&i.SelectedModel,
		&i.Role,
		&i.Status,
		&i.ModelsCache,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, company_id, name, base_url, token_enc, proto, vendor, selected_model, role, status, models_cache, created_at, updated_at FROM endpoint WHERE id = ?
`

func (q *Queries) GetEndpoint(ctx context.Context, id string) (Endpoint, error) {
	row := q.db.QueryRowContext(ctx, getEndpoint, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.BaseUrl,
		&i.TokenEnc,
		&i.Proto,
		&i.Vendor,
		&i.SelectedModel,
		&i.Role,
		&i.Status,
		&i.ModelsCache,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, company_id, name, base_url, token_enc, proto, vendor, selected_model, role, status, models_cache, created_at, updated_at FROM endpoint WHERE company_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListEndpoints(ctx context.Context, companyID string) ([]Endpoint, error) {
	rows, err := q.db.QueryContext(ctx, listEndpoints, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.BaseUrl,
			&i.TokenEnc,
			&i.Proto,
			&i.Vendor,
			&i.SelectedModel,
			&i.Role,
			&i.Status,
			&i.ModelsCache,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpointModel = `-- name: UpdateEndpointModel :one
UPDATE endpoint SET selected_model = ?, models_cache = ?, updated_at = ? WHERE id = ? RETURNING id, company_id, name, base_url, token_enc, proto, vendor, selected_model, role, status, models_cache, created_at, updated_at
`

type UpdateEndpointModelParams struct {
	SelectedModel string `json:"selected_model"`
	ModelsCache   string `json:"models_cache"`
	UpdatedAt     int64  `json:"updated_at"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateEndpointModel(ctx context.Context, arg UpdateEndpointModelParams) (Endpoint, error) {
	row := q.db.QueryRowContext(ctx, updateEndpointModel,
		arg.SelectedModel,
		arg.ModelsCache,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.BaseUrl,
		&i.TokenEnc,
		&i.Proto,
		&i.Vendor,
		&i.SelectedModel,
		&i.Role,
		&i.Status,
		&i.ModelsCache,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEndpointRole = `-- name: UpdateEndpointRole :one
UPDATE endpoint SET role = ?, updated_at = ? WHERE id = ? RETURNING id, company_id, name, base_url, token_enc, proto, vendor, selected_model, role, status, models_cache, created_at, updated_at
`

type UpdateEndpointRoleParams struct {
	Role      string `json:"role"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateEndpointRole(ctx context.Context, arg UpdateEndpointRoleParams) (Endpoint, error) {
	row := q.db.QueryRowContext(ctx, updateEndpointRole, arg.Role, arg.UpdatedAt, arg.ID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.BaseUrl,
		&i.TokenEnc,
		&i.Proto,
		&i.Vendor,
		&i.SelectedModel,
		&i.Role,
		&i.Status,
		&i.ModelsCache,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEndpointStatus = `-- name: UpdateEndpointStatus :one
UPDATE endpoint SET status = ?, updated_at = ? WHERE id = ? RETURNING id, company_id, name, base_url, token_enc, proto, vendor, selected_model, role, status, models_cache, created_at, updated_at
`

type UpdateEndpointStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateEndpointStatus(ctx context.Context, arg UpdateEndpointStatusParams) (Endpoint, error) {
	row := q.db.QueryRowContext(ctx, updateEndpointStatus, arg.Status, arg.UpdatedAt, arg.ID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.BaseUrl,
		&i.TokenEnc,
		&i.Proto,
		&i.Vendor,
		&i.SelectedModel,
		&i.Role,
		&i.Status,
		&i.ModelsCache,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
