// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution.sql

package query

import (
	"context"
	"database/sql"
)

const createExecution = `-- name: CreateExecution :one
INSERT INTO execution (id, task_id, worker_id, attempt, status, started_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, task_id, worker_id, attempt, status, started_at, finished_at, result, error, created_at
`

type CreateExecutionParams struct {
	ID        string `json:"id"`
	TaskID    string `json:"task_id"`
	WorkerID  string `json:"worker_id"`
	Attempt   int64  `json:"attempt"`
	Status    string `json:"status"`
	StartedAt int64  `json:"started_at"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRowContext(ctx, createExecution,
		arg.ID,
		arg.TaskID,
		arg.WorkerID,
		arg.Attempt,
		arg.Status,
		arg.StartedAt,
		arg.CreatedAt,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.WorkerID,
		&i.Attempt,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const finishExecution = `-- name: FinishExecution :one
UPDATE execution
SET status = ?, finished_at = ?, result = ?, error = ?
WHERE id = ?
RETURNING id, task_id, worker_id, attempt, status, started_at, finished_at, result, error, created_at
`

type FinishExecutionParams struct {
	Status     string        `json:"status"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
	Result     string        `json:"result"`
	Error      string        `json:"error"`
	ID         string        `json:"id"`
}

func (q *Queries) FinishExecution(ctx context.Context, arg FinishExecutionParams) (Execution, error) {
	row := q.db.QueryRowContext(ctx, finishExecution,
		arg.Status,
		arg.FinishedAt,
		arg.Result,
		arg.Error,
		arg.ID,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.WorkerID,
		&i.Attempt,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getExecution = `-- name: GetExecution :one
SELECT id, task_id, worker_id, attempt, status, started_at, finished_at, result, error, created_at FROM execution WHERE id = ?
`

func (q *Queries) GetExecution(ctx context.Context, id string) (Execution, error) {
	row := q.db.QueryRowContext(ctx, getExecution, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.WorkerID,
		&i.Attempt,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listExecutions = `-- name: ListExecutions :many
SELECT id, task_id, worker_id, attempt, status, started_at, finished_at, result, error, created_at FROM execution
WHERE (?1 = '' OR task_id = ?2)
  AND (?3 = '' OR status = ?4)
ORDER BY created_at DESC
`

type ListExecutionsParams struct {
	TaskFilter   interface{} `json:"task_filter"`
	TaskID       string      `json:"task_id"`
	StatusFilter interface{} `json:"status_filter"`
	Status       string      `json:"status"`
}

func (q *Queries) ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, listExecutions,
		arg.TaskFilter,
		arg.TaskID,
		arg.StatusFilter,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Execution{}
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.WorkerID,
			&i.Attempt,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Result,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
