// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memory.sql

package query

import (
	"context"
)

const createMemory = `-- name: CreateMemory :one
INSERT INTO memory (id, company_id, type, title, content, source, tags, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, company_id, type, title, content, source, tags, created_at, updated_at
`

type CreateMemoryParams struct {
	ID        string `json:"id"`
	CompanyID string `json:"company_id"`
	Type      string `json:"type"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Source    string `json:"source"`
	Tags      string `json:"tags"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, createMemory,
		arg.ID,
		arg.CompanyID,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.Source,
		arg.Tags,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.Source,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemory = `-- name: GetMemory :one
SELECT id, company_id, type, title, content, source, tags, created_at, updated_at FROM memory WHERE id = ?
`

func (q *Queries) GetMemory(ctx context.Context, id string) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemory, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.Source,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemories = `-- name: ListMemories :many
SELECT id, company_id, type, title, content, source, tags, created_at, updated_at FROM memory
WHERE (?1 = '' OR company_id = ?2)
  AND (?3 = '' OR type = ?4)
ORDER BY created_at DESC
`

type ListMemoriesParams struct {
	CompanyFilter interface{} `json:"company_filter"`
	CompanyID     string      `json:"company_id"`
	TypeFilter    interface{} `json:"type_filter"`
	Type          string      `json:"type"`
}

func (q *Queries) ListMemories(ctx context.Context, arg ListMemoriesParams) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listMemories,
		arg.CompanyFilter,
		arg.CompanyID,
		arg.TypeFilter,
		arg.Type,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Source,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
