// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"database/sql"
)

type Agent struct {
	ID           string `json:"id"`
	CapabilityID string `json:"capability_id"`
	Name         string `json:"name"`
	Role         string `json:"role"`
	ModelHint    string `json:"model_hint"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type Audit struct {
	ID         string `json:"id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Action     string `json:"action"`
	Actor      string `json:"actor"`
	Detail     string `json:"detail"`
	CreatedAt  int64  `json:"created_at"`
}

type Capability struct {
	ID          string `json:"id"`
	CompanyID   string `json:"company_id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type Company struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Vision    string `json:"vision"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Permission struct {
	ID        string `json:"id"`
	PolicyID  string `json:"policy_id"`
	Subject   string `json:"subject"`
	Action    string `json:"action"`
	Resource  string `json:"resource"`
	CreatedAt int64  `json:"created_at"`
}

type Policy struct {
	ID        string `json:"id"`
	CompanyID string `json:"company_id"`
	Name      string `json:"name"`
	Kind      string `json:"kind"`
	Statement string `json:"statement"`
	Enabled   int64  `json:"enabled"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Task struct {
	ID           string         `json:"id"`
	CompanyID    string         `json:"company_id"`
	CapabilityID sql.NullString `json:"capability_id"`
	WorkflowID   sql.NullString `json:"workflow_id"`
	AgentID      sql.NullString `json:"agent_id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Status       string         `json:"status"`
	Priority     int64          `json:"priority"`
	Attempt      int64          `json:"attempt"`
	Risk         string         `json:"risk"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

type Workflow struct {
	ID          string `json:"id"`
	CompanyID   string `json:"company_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Definition  string `json:"definition"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}
