// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"database/sql"
)

type Agent struct {
	ID           string `json:"id"`
	CapabilityID string `json:"capability_id"`
	Name         string `json:"name"`
	Role         string `json:"role"`
	ModelHint    string `json:"model_hint"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type Approval struct {
	ID           string        `json:"id"`
	TaskID       string        `json:"task_id"`
	Risk         string        `json:"risk"`
	Reason       string        `json:"reason"`
	Status       string        `json:"status"`
	RequestedBy  string        `json:"requested_by"`
	DecidedBy    string        `json:"decided_by"`
	DecisionNote string        `json:"decision_note"`
	CreatedAt    int64         `json:"created_at"`
	DecidedAt    sql.NullInt64 `json:"decided_at"`
}

type Audit struct {
	ID         string `json:"id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Action     string `json:"action"`
	Actor      string `json:"actor"`
	Detail     string `json:"detail"`
	CreatedAt  int64  `json:"created_at"`
}

type Capability struct {
	ID          string `json:"id"`
	CompanyID   string `json:"company_id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

type Company struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Vision    string `json:"vision"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Decision struct {
	ID        string `json:"id"`
	CompanyID string `json:"company_id"`
	Title     string `json:"title"`
	Kind      string `json:"kind"`
	Status    string `json:"status"`
	Body      string `json:"body"`
	DecidedBy string `json:"decided_by"`
	Source    string `json:"source"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Endpoint struct {
	ID            string `json:"id"`
	CompanyID     string `json:"company_id"`
	Name          string `json:"name"`
	BaseUrl       string `json:"base_url"`
	TokenEnc      string `json:"token_enc"`
	Proto         string `json:"proto"`
	Vendor        string `json:"vendor"`
	SelectedModel string `json:"selected_model"`
	Role          string `json:"role"`
	Status        string `json:"status"`
	ModelsCache   string `json:"models_cache"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

type Execution struct {
	ID         string        `json:"id"`
	TaskID     string        `json:"task_id"`
	WorkerID   string        `json:"worker_id"`
	Attempt    int64         `json:"attempt"`
	Status     string        `json:"status"`
	StartedAt  int64         `json:"started_at"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
	Result     string        `json:"result"`
	Error      string        `json:"error"`
	CreatedAt  int64         `json:"created_at"`
}

type Memory struct {
	ID        string `json:"id"`
	CompanyID string `json:"company_id"`
	Type      string `json:"type"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Source    string `json:"source"`
	Tags      string `json:"tags"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Permission struct {
	ID        string `json:"id"`
	PolicyID  string `json:"policy_id"`
	Subject   string `json:"subject"`
	Action    string `json:"action"`
	Resource  string `json:"resource"`
	CreatedAt int64  `json:"created_at"`
}

type Policy struct {
	ID        string `json:"id"`
	CompanyID string `json:"company_id"`
	Name      string `json:"name"`
	Kind      string `json:"kind"`
	Statement string `json:"statement"`
	Enabled   int64  `json:"enabled"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type Task struct {
	ID                 string         `json:"id"`
	CompanyID          string         `json:"company_id"`
	CapabilityID       sql.NullString `json:"capability_id"`
	WorkflowID         sql.NullString `json:"workflow_id"`
	AgentID            sql.NullString `json:"agent_id"`
	Title              string         `json:"title"`
	Description        string         `json:"description"`
	ToolName           string         `json:"tool_name"`
	Status             string         `json:"status"`
	Priority           int64          `json:"priority"`
	Attempt            int64          `json:"attempt"`
	Risk               string         `json:"risk"`
	Qstatus            string         `json:"qstatus"`
	LeaseWorkerID      string         `json:"lease_worker_id"`
	LeaseUntil         int64          `json:"lease_until"`
	MaxAttempts        int64          `json:"max_attempts"`
	TimeoutSec         int64          `json:"timeout_sec"`
	LastError          string         `json:"last_error"`
	Result             string         `json:"result"`
	WorkspacePath      string         `json:"workspace_path"`
	ParentTaskID       sql.NullString `json:"parent_task_id"`
	RoundNo            int64          `json:"round_no"`
	ConflictCount      int64          `json:"conflict_count"`
	WriterEndpointID   sql.NullString `json:"writer_endpoint_id"`
	ReviewerEndpointID sql.NullString `json:"reviewer_endpoint_id"`
	CreatedAt          int64          `json:"created_at"`
	UpdatedAt          int64          `json:"updated_at"`
}

type Workflow struct {
	ID          string `json:"id"`
	CompanyID   string `json:"company_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Definition  string `json:"definition"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}
