// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission.sql

package query

import (
	"context"
)

const checkPermission = `-- name: CheckPermission :one
SELECT COUNT(*) FROM permission p
JOIN policy po ON po.id = p.policy_id
WHERE p.subject = ? AND p.action = ? AND p.resource = ? AND po.enabled = 1 AND po.kind = 'allow'
`

type CheckPermissionParams struct {
	Subject  string `json:"subject"`
	Action   string `json:"action"`
	Resource string `json:"resource"`
}

func (q *Queries) CheckPermission(ctx context.Context, arg CheckPermissionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkPermission, arg.Subject, arg.Action, arg.Resource)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO permission (id, policy_id, subject, action, resource, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, policy_id, subject, "action", resource, created_at
`

type CreatePermissionParams struct {
	ID        string `json:"id"`
	PolicyID  string `json:"policy_id"`
	Subject   string `json:"subject"`
	Action    string `json:"action"`
	Resource  string `json:"resource"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRowContext(ctx, createPermission,
		arg.ID,
		arg.PolicyID,
		arg.Subject,
		arg.Action,
		arg.Resource,
		arg.CreatedAt,
	)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.PolicyID,
		&i.Subject,
		&i.Action,
		&i.Resource,
		&i.CreatedAt,
	)
	return i, err
}

const listPermissionsByPolicy = `-- name: ListPermissionsByPolicy :many
SELECT id, policy_id, subject, "action", resource, created_at FROM permission WHERE policy_id = ? ORDER BY created_at
`

func (q *Queries) ListPermissionsByPolicy(ctx context.Context, policyID string) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissionsByPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.Subject,
			&i.Action,
			&i.Resource,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
