// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pipeline.sql

package query

import (
	"context"
)

const createPipeline = `-- name: CreatePipeline :one
INSERT INTO pipelines (id, project_id, name, kind, description, risk, status, schedule, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, name, kind, description, risk, status, schedule, plan_policy, created_at, updated_at
`

type CreatePipelineParams struct {
	ID          string `json:"id"`
	ProjectID   string `json:"project_id"`
	Name        string `json:"name"`
	Kind        string `json:"kind"`
	Description string `json:"description"`
	Risk        string `json:"risk"`
	Status      string `json:"status"`
	Schedule    string `json:"schedule"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, createPipeline,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Kind,
		arg.Description,
		arg.Risk,
		arg.Status,
		arg.Schedule,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Risk,
		&i.Status,
		&i.Schedule,
		&i.PlanPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePipeline = `-- name: DeletePipeline :execrows
DELETE FROM pipelines WHERE id = ?
`

func (q *Queries) DeletePipeline(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePipeline, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePipelinesByProject = `-- name: DeletePipelinesByProject :execrows
DELETE FROM pipelines WHERE project_id = ?
`

func (q *Queries) DeletePipelinesByProject(ctx context.Context, projectID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePipelinesByProject, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPipeline = `-- name: GetPipeline :one
SELECT id, project_id, name, kind, description, risk, status, schedule, plan_policy, created_at, updated_at FROM pipelines WHERE id = ?
`

func (q *Queries) GetPipeline(ctx context.Context, id string) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, getPipeline, id)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Risk,
		&i.Status,
		&i.Schedule,
		&i.PlanPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPipelinesByProject = `-- name: ListPipelinesByProject :many
SELECT id, project_id, name, kind, description, risk, status, schedule, plan_policy, created_at, updated_at FROM pipelines WHERE project_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListPipelinesByProject(ctx context.Context, projectID string) ([]Pipeline, error) {
	rows, err := q.db.QueryContext(ctx, listPipelinesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pipeline{}
	for rows.Next() {
		var i Pipeline
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Kind,
			&i.Description,
			&i.Risk,
			&i.Status,
			&i.Schedule,
			&i.PlanPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledPipelines = `-- name: ListScheduledPipelines :many
SELECT id, project_id, name, kind, schedule FROM pipelines
WHERE status = 'active' AND schedule != ''
ORDER BY created_at ASC
`

type ListScheduledPipelinesRow struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
	Kind      string `json:"kind"`
	Schedule  string `json:"schedule"`
}

func (q *Queries) ListScheduledPipelines(ctx context.Context) ([]ListScheduledPipelinesRow, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledPipelines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduledPipelinesRow{}
	for rows.Next() {
		var i ListScheduledPipelinesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Kind,
			&i.Schedule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPipelinePlanPolicy = `-- name: SetPipelinePlanPolicy :one
UPDATE pipelines SET plan_policy = ?, updated_at = ? WHERE id = ? RETURNING id, project_id, name, kind, description, risk, status, schedule, plan_policy, created_at, updated_at
`

type SetPipelinePlanPolicyParams struct {
	PlanPolicy string `json:"plan_policy"`
	UpdatedAt  int64  `json:"updated_at"`
	ID         string `json:"id"`
}

func (q *Queries) SetPipelinePlanPolicy(ctx context.Context, arg SetPipelinePlanPolicyParams) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, setPipelinePlanPolicy, arg.PlanPolicy, arg.UpdatedAt, arg.ID)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Risk,
		&i.Status,
		&i.Schedule,
		&i.PlanPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePipelineSchedule = `-- name: UpdatePipelineSchedule :one
UPDATE pipelines SET schedule = ?, updated_at = ? WHERE id = ? RETURNING id, project_id, name, kind, description, risk, status, schedule, plan_policy, created_at, updated_at
`

type UpdatePipelineScheduleParams struct {
	Schedule  string `json:"schedule"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UpdatePipelineSchedule(ctx context.Context, arg UpdatePipelineScheduleParams) (Pipeline, error) {
	row := q.db.QueryRowContext(ctx, updatePipelineSchedule, arg.Schedule, arg.UpdatedAt, arg.ID)
	var i Pipeline
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Description,
		&i.Risk,
		&i.Status,
		&i.Schedule,
		&i.PlanPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
