// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan.sql

package query

import (
	"context"
	"database/sql"
)

const createPlanPhase = `-- name: CreatePlanPhase :one
INSERT INTO task_plan_phase (id, plan_id, seq, kind, title, allocator, status, evidence, note, started_at, finished_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, plan_id, seq, kind, title, allocator, status, evidence, note, started_at, finished_at
`

type CreatePlanPhaseParams struct {
	ID         string        `json:"id"`
	PlanID     string        `json:"plan_id"`
	Seq        int64         `json:"seq"`
	Kind       string        `json:"kind"`
	Title      string        `json:"title"`
	Allocator  string        `json:"allocator"`
	Status     string        `json:"status"`
	Evidence   string        `json:"evidence"`
	Note       string        `json:"note"`
	StartedAt  sql.NullInt64 `json:"started_at"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
}

func (q *Queries) CreatePlanPhase(ctx context.Context, arg CreatePlanPhaseParams) (TaskPlanPhase, error) {
	row := q.db.QueryRowContext(ctx, createPlanPhase,
		arg.ID,
		arg.PlanID,
		arg.Seq,
		arg.Kind,
		arg.Title,
		arg.Allocator,
		arg.Status,
		arg.Evidence,
		arg.Note,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i TaskPlanPhase
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Seq,
		&i.Kind,
		&i.Title,
		&i.Allocator,
		&i.Status,
		&i.Evidence,
		&i.Note,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createTaskPlan = `-- name: CreateTaskPlan :one
INSERT INTO task_plan (id, task_id, kind, materialized, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, task_id, kind, materialized, created_at, updated_at
`

type CreateTaskPlanParams struct {
	ID           string `json:"id"`
	TaskID       string `json:"task_id"`
	Kind         string `json:"kind"`
	Materialized string `json:"materialized"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) CreateTaskPlan(ctx context.Context, arg CreateTaskPlanParams) (TaskPlan, error) {
	row := q.db.QueryRowContext(ctx, createTaskPlan,
		arg.ID,
		arg.TaskID,
		arg.Kind,
		arg.Materialized,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TaskPlan
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.Materialized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanPhase = `-- name: GetPlanPhase :one
SELECT id, plan_id, seq, kind, title, allocator, status, evidence, note, started_at, finished_at FROM task_plan_phase WHERE id = ?
`

func (q *Queries) GetPlanPhase(ctx context.Context, id string) (TaskPlanPhase, error) {
	row := q.db.QueryRowContext(ctx, getPlanPhase, id)
	var i TaskPlanPhase
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Seq,
		&i.Kind,
		&i.Title,
		&i.Allocator,
		&i.Status,
		&i.Evidence,
		&i.Note,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getTaskPlanByTask = `-- name: GetTaskPlanByTask :one
SELECT id, task_id, kind, materialized, created_at, updated_at FROM task_plan WHERE task_id = ?
`

func (q *Queries) GetTaskPlanByTask(ctx context.Context, taskID string) (TaskPlan, error) {
	row := q.db.QueryRowContext(ctx, getTaskPlanByTask, taskID)
	var i TaskPlan
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Kind,
		&i.Materialized,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlanPhases = `-- name: ListPlanPhases :many
SELECT id, plan_id, seq, kind, title, allocator, status, evidence, note, started_at, finished_at FROM task_plan_phase WHERE plan_id = ? ORDER BY seq ASC
`

func (q *Queries) ListPlanPhases(ctx context.Context, planID string) ([]TaskPlanPhase, error) {
	rows, err := q.db.QueryContext(ctx, listPlanPhases, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskPlanPhase{}
	for rows.Next() {
		var i TaskPlanPhase
		if err := rows.Scan(
			&i.ID,
			&i.PlanID,
			&i.Seq,
			&i.Kind,
			&i.Title,
			&i.Allocator,
			&i.Status,
			&i.Evidence,
			&i.Note,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replacePlanPhase = `-- name: ReplacePlanPhase :one
UPDATE task_plan_phase
SET status = ?, evidence = ?, note = ?, started_at = ?, finished_at = ?
WHERE id = ?
RETURNING id, plan_id, seq, kind, title, allocator, status, evidence, note, started_at, finished_at
`

type ReplacePlanPhaseParams struct {
	Status     string        `json:"status"`
	Evidence   string        `json:"evidence"`
	Note       string        `json:"note"`
	StartedAt  sql.NullInt64 `json:"started_at"`
	FinishedAt sql.NullInt64 `json:"finished_at"`
	ID         string        `json:"id"`
}

func (q *Queries) ReplacePlanPhase(ctx context.Context, arg ReplacePlanPhaseParams) (TaskPlanPhase, error) {
	row := q.db.QueryRowContext(ctx, replacePlanPhase,
		arg.Status,
		arg.Evidence,
		arg.Note,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i TaskPlanPhase
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.Seq,
		&i.Kind,
		&i.Title,
		&i.Allocator,
		&i.Status,
		&i.Evidence,
		&i.Note,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const setPlanUpdated = `-- name: SetPlanUpdated :exec
UPDATE task_plan SET updated_at = ? WHERE id = ?
`

type SetPlanUpdatedParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) SetPlanUpdated(ctx context.Context, arg SetPlanUpdatedParams) error {
	_, err := q.db.ExecContext(ctx, setPlanUpdated, arg.UpdatedAt, arg.ID)
	return err
}
