// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy.sql

package query

import (
	"context"
)

const createPolicy = `-- name: CreatePolicy :one
INSERT INTO policy (id, company_id, name, kind, statement, enabled, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, company_id, name, kind, statement, enabled, created_at, updated_at
`

type CreatePolicyParams struct {
	ID        string `json:"id"`
	CompanyID string `json:"company_id"`
	Name      string `json:"name"`
	Kind      string `json:"kind"`
	Statement string `json:"statement"`
	Enabled   int64  `json:"enabled"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreatePolicy(ctx context.Context, arg CreatePolicyParams) (Policy, error) {
	row := q.db.QueryRowContext(ctx, createPolicy,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Kind,
		arg.Statement,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Kind,
		&i.Statement,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicy = `-- name: GetPolicy :one
SELECT id, company_id, name, kind, statement, enabled, created_at, updated_at FROM policy WHERE id = ?
`

func (q *Queries) GetPolicy(ctx context.Context, id string) (Policy, error) {
	row := q.db.QueryRowContext(ctx, getPolicy, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Kind,
		&i.Statement,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPoliciesByCompany = `-- name: ListPoliciesByCompany :many
SELECT id, company_id, name, kind, statement, enabled, created_at, updated_at FROM policy WHERE company_id = ? ORDER BY created_at
`

func (q *Queries) ListPoliciesByCompany(ctx context.Context, companyID string) ([]Policy, error) {
	rows, err := q.db.QueryContext(ctx, listPoliciesByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Kind,
			&i.Statement,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
