// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package query

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, company_id, name, root_path, description, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, company_id, name, root_path, description, created_at, updated_at
`

type CreateProjectParams struct {
	ID          string `json:"id"`
	CompanyID   string `json:"company_id"`
	Name        string `json:"name"`
	RootPath    string `json:"root_path"`
	Description string `json:"description"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.RootPath,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.RootPath,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getProject = `-- name: GetProject :one
SELECT id, company_id, name, root_path, description, created_at, updated_at FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.RootPath,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByCompany = `-- name: ListProjectsByCompany :many
SELECT id, company_id, name, root_path, description, created_at, updated_at FROM projects WHERE company_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByCompany(ctx context.Context, companyID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.RootPath,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
