// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repo.sql

package query

import (
	"context"
	"database/sql"
)

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (id, company_id, name, repo_url, workspace_path, created_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, company_id, name, repo_url, workspace_path, created_at
`

type CreateRepoParams struct {
	ID            string `json:"id"`
	CompanyID     string `json:"company_id"`
	Name          string `json:"name"`
	RepoUrl       string `json:"repo_url"`
	WorkspacePath string `json:"workspace_path"`
	CreatedAt     int64  `json:"created_at"`
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRowContext(ctx, createRepo,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.RepoUrl,
		arg.WorkspacePath,
		arg.CreatedAt,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.RepoUrl,
		&i.WorkspacePath,
		&i.CreatedAt,
	)
	return i, err
}

const getIssueSync = `-- name: GetIssueSync :one
SELECT id, company_id, repo_id, issue_number, title, disposition, task_id, note, created_at FROM issue_sync WHERE repo_id = ? AND issue_number = ?
`

type GetIssueSyncParams struct {
	RepoID      string `json:"repo_id"`
	IssueNumber int64  `json:"issue_number"`
}

func (q *Queries) GetIssueSync(ctx context.Context, arg GetIssueSyncParams) (IssueSync, error) {
	row := q.db.QueryRowContext(ctx, getIssueSync, arg.RepoID, arg.IssueNumber)
	var i IssueSync
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.RepoID,
		&i.IssueNumber,
		&i.Title,
		&i.Disposition,
		&i.TaskID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getRepo = `-- name: GetRepo :one
SELECT id, company_id, name, repo_url, workspace_path, created_at FROM repos WHERE id = ?
`

func (q *Queries) GetRepo(ctx context.Context, id string) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.RepoUrl,
		&i.WorkspacePath,
		&i.CreatedAt,
	)
	return i, err
}

const listAllRepos = `-- name: ListAllRepos :many
SELECT id, company_id, name, repo_url, workspace_path, created_at FROM repos ORDER BY company_id, created_at DESC
`

func (q *Queries) ListAllRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listAllRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repo{}
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.RepoUrl,
			&i.WorkspacePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueSync = `-- name: ListIssueSync :many
SELECT id, company_id, repo_id, issue_number, title, disposition, task_id, note, created_at FROM issue_sync WHERE company_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListIssueSync(ctx context.Context, companyID string) ([]IssueSync, error) {
	rows, err := q.db.QueryContext(ctx, listIssueSync, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueSync{}
	for rows.Next() {
		var i IssueSync
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.RepoID,
			&i.IssueNumber,
			&i.Title,
			&i.Disposition,
			&i.TaskID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepos = `-- name: ListRepos :many
SELECT id, company_id, name, repo_url, workspace_path, created_at FROM repos WHERE company_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListRepos(ctx context.Context, companyID string) ([]Repo, error) {
	rows, err := q.db.QueryContext(ctx, listRepos, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repo{}
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.RepoUrl,
			&i.WorkspacePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIssueSync = `-- name: UpsertIssueSync :one
INSERT INTO issue_sync (id, company_id, repo_id, issue_number, title, disposition, task_id, note, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(repo_id, issue_number) DO UPDATE SET
    title = excluded.title,
    disposition = excluded.disposition,
    task_id = excluded.task_id,
    note = excluded.note
RETURNING id, company_id, repo_id, issue_number, title, disposition, task_id, note, created_at
`

type UpsertIssueSyncParams struct {
	ID          string         `json:"id"`
	CompanyID   string         `json:"company_id"`
	RepoID      string         `json:"repo_id"`
	IssueNumber int64          `json:"issue_number"`
	Title       string         `json:"title"`
	Disposition string         `json:"disposition"`
	TaskID      sql.NullString `json:"task_id"`
	Note        string         `json:"note"`
	CreatedAt   int64          `json:"created_at"`
}

func (q *Queries) UpsertIssueSync(ctx context.Context, arg UpsertIssueSyncParams) (IssueSync, error) {
	row := q.db.QueryRowContext(ctx, upsertIssueSync,
		arg.ID,
		arg.CompanyID,
		arg.RepoID,
		arg.IssueNumber,
		arg.Title,
		arg.Disposition,
		arg.TaskID,
		arg.Note,
		arg.CreatedAt,
	)
	var i IssueSync
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.RepoID,
		&i.IssueNumber,
		&i.Title,
		&i.Disposition,
		&i.TaskID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}
