// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package query

import (
	"context"
	"database/sql"
)

const deleteCompanySetting = `-- name: DeleteCompanySetting :exec
DELETE FROM company_setting WHERE company_id = ?
`

func (q *Queries) DeleteCompanySetting(ctx context.Context, companyID string) error {
	_, err := q.db.ExecContext(ctx, deleteCompanySetting, companyID)
	return err
}

const deleteProjectSecret = `-- name: DeleteProjectSecret :exec
DELETE FROM project_secret WHERE project_id = ? AND id = ?
`

type DeleteProjectSecretParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) DeleteProjectSecret(ctx context.Context, arg DeleteProjectSecretParams) error {
	_, err := q.db.ExecContext(ctx, deleteProjectSecret, arg.ProjectID, arg.ID)
	return err
}

const deleteSecret = `-- name: DeleteSecret :exec
DELETE FROM secret WHERE company_id = ? AND id = ?
`

type DeleteSecretParams struct {
	CompanyID string `json:"company_id"`
	ID        string `json:"id"`
}

func (q *Queries) DeleteSecret(ctx context.Context, arg DeleteSecretParams) error {
	_, err := q.db.ExecContext(ctx, deleteSecret, arg.CompanyID, arg.ID)
	return err
}

const getAppSetting = `-- name: GetAppSetting :one
SELECT id, engine_mode_default, agent_cli_default, console_token_hash, digest_time, http_port, poll_min, queue_work, queue_interval_sec, schedule_poll_sec, updated_at FROM app_setting WHERE id = ?
`

func (q *Queries) GetAppSetting(ctx context.Context, id string) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getAppSetting, id)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.EngineModeDefault,
		&i.AgentCliDefault,
		&i.ConsoleTokenHash,
		&i.DigestTime,
		&i.HttpPort,
		&i.PollMin,
		&i.QueueWork,
		&i.QueueIntervalSec,
		&i.SchedulePollSec,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanySetting = `-- name: GetCompanySetting :one
SELECT company_id, engine_mode, agent_cli, issue_source, issue_fixture_path, updated_at FROM company_setting WHERE company_id = ?
`

func (q *Queries) GetCompanySetting(ctx context.Context, companyID string) (CompanySetting, error) {
	row := q.db.QueryRowContext(ctx, getCompanySetting, companyID)
	var i CompanySetting
	err := row.Scan(
		&i.CompanyID,
		&i.EngineMode,
		&i.AgentCli,
		&i.IssueSource,
		&i.IssueFixturePath,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectSecret = `-- name: GetProjectSecret :one
SELECT project_id, id, cipher, updated_at FROM project_secret WHERE project_id = ? AND id = ?
`

type GetProjectSecretParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) GetProjectSecret(ctx context.Context, arg GetProjectSecretParams) (ProjectSecret, error) {
	row := q.db.QueryRowContext(ctx, getProjectSecret, arg.ProjectID, arg.ID)
	var i ProjectSecret
	err := row.Scan(
		&i.ProjectID,
		&i.ID,
		&i.Cipher,
		&i.UpdatedAt,
	)
	return i, err
}

const getSecret = `-- name: GetSecret :one
SELECT company_id, id, cipher, updated_at FROM secret WHERE company_id = ? AND id = ?
`

type GetSecretParams struct {
	CompanyID string `json:"company_id"`
	ID        string `json:"id"`
}

func (q *Queries) GetSecret(ctx context.Context, arg GetSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecret, arg.CompanyID, arg.ID)
	var i Secret
	err := row.Scan(
		&i.CompanyID,
		&i.ID,
		&i.Cipher,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAppSetting = `-- name: InsertAppSetting :one
INSERT INTO app_setting (id, engine_mode_default, agent_cli_default, console_token_hash, digest_time, http_port, poll_min, queue_work, queue_interval_sec, schedule_poll_sec, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, engine_mode_default, agent_cli_default, console_token_hash, digest_time, http_port, poll_min, queue_work, queue_interval_sec, schedule_poll_sec, updated_at
`

type InsertAppSettingParams struct {
	ID                string `json:"id"`
	EngineModeDefault string `json:"engine_mode_default"`
	AgentCliDefault   string `json:"agent_cli_default"`
	ConsoleTokenHash  string `json:"console_token_hash"`
	DigestTime        string `json:"digest_time"`
	HttpPort          int64  `json:"http_port"`
	PollMin           int64  `json:"poll_min"`
	QueueWork         int64  `json:"queue_work"`
	QueueIntervalSec  int64  `json:"queue_interval_sec"`
	SchedulePollSec   int64  `json:"schedule_poll_sec"`
	UpdatedAt         int64  `json:"updated_at"`
}

func (q *Queries) InsertAppSetting(ctx context.Context, arg InsertAppSettingParams) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, insertAppSetting,
		arg.ID,
		arg.EngineModeDefault,
		arg.AgentCliDefault,
		arg.ConsoleTokenHash,
		arg.DigestTime,
		arg.HttpPort,
		arg.PollMin,
		arg.QueueWork,
		arg.QueueIntervalSec,
		arg.SchedulePollSec,
		arg.UpdatedAt,
	)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.EngineModeDefault,
		&i.AgentCliDefault,
		&i.ConsoleTokenHash,
		&i.DigestTime,
		&i.HttpPort,
		&i.PollMin,
		&i.QueueWork,
		&i.QueueIntervalSec,
		&i.SchedulePollSec,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCompanySetting = `-- name: InsertCompanySetting :one
INSERT INTO company_setting (company_id, engine_mode, agent_cli, issue_source, issue_fixture_path, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING company_id, engine_mode, agent_cli, issue_source, issue_fixture_path, updated_at
`

type InsertCompanySettingParams struct {
	CompanyID        string         `json:"company_id"`
	EngineMode       sql.NullString `json:"engine_mode"`
	AgentCli         sql.NullString `json:"agent_cli"`
	IssueSource      sql.NullString `json:"issue_source"`
	IssueFixturePath sql.NullString `json:"issue_fixture_path"`
	UpdatedAt        int64          `json:"updated_at"`
}

func (q *Queries) InsertCompanySetting(ctx context.Context, arg InsertCompanySettingParams) (CompanySetting, error) {
	row := q.db.QueryRowContext(ctx, insertCompanySetting,
		arg.CompanyID,
		arg.EngineMode,
		arg.AgentCli,
		arg.IssueSource,
		arg.IssueFixturePath,
		arg.UpdatedAt,
	)
	var i CompanySetting
	err := row.Scan(
		&i.CompanyID,
		&i.EngineMode,
		&i.AgentCli,
		&i.IssueSource,
		&i.IssueFixturePath,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProjectSecret = `-- name: InsertProjectSecret :one
INSERT INTO project_secret (project_id, id, cipher, updated_at)
VALUES (?, ?, ?, ?)
RETURNING project_id, id, cipher, updated_at
`

type InsertProjectSecretParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
	Cipher    string `json:"cipher"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) InsertProjectSecret(ctx context.Context, arg InsertProjectSecretParams) (ProjectSecret, error) {
	row := q.db.QueryRowContext(ctx, insertProjectSecret,
		arg.ProjectID,
		arg.ID,
		arg.Cipher,
		arg.UpdatedAt,
	)
	var i ProjectSecret
	err := row.Scan(
		&i.ProjectID,
		&i.ID,
		&i.Cipher,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSecret = `-- name: InsertSecret :one
INSERT INTO secret (company_id, id, cipher, updated_at)
VALUES (?, ?, ?, ?)
RETURNING company_id, id, cipher, updated_at
`

type InsertSecretParams struct {
	CompanyID string `json:"company_id"`
	ID        string `json:"id"`
	Cipher    string `json:"cipher"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) InsertSecret(ctx context.Context, arg InsertSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, insertSecret,
		arg.CompanyID,
		arg.ID,
		arg.Cipher,
		arg.UpdatedAt,
	)
	var i Secret
	err := row.Scan(
		&i.CompanyID,
		&i.ID,
		&i.Cipher,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectSecrets = `-- name: ListProjectSecrets :many
SELECT project_id, id, cipher, updated_at FROM project_secret WHERE project_id = ? ORDER BY id
`

func (q *Queries) ListProjectSecrets(ctx context.Context, projectID string) ([]ProjectSecret, error) {
	rows, err := q.db.QueryContext(ctx, listProjectSecrets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectSecret{}
	for rows.Next() {
		var i ProjectSecret
		if err := rows.Scan(
			&i.ProjectID,
			&i.ID,
			&i.Cipher,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecrets = `-- name: ListSecrets :many
SELECT company_id, id, cipher, updated_at FROM secret WHERE company_id = ? ORDER BY id
`

func (q *Queries) ListSecrets(ctx context.Context, companyID string) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, listSecrets, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.CompanyID,
			&i.ID,
			&i.Cipher,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppSetting = `-- name: UpdateAppSetting :one
UPDATE app_setting SET engine_mode_default = ?, agent_cli_default = ?, console_token_hash = ?, digest_time = ?, http_port = ?, poll_min = ?, queue_work = ?, queue_interval_sec = ?, schedule_poll_sec = ?, updated_at = ? WHERE id = ? RETURNING id, engine_mode_default, agent_cli_default, console_token_hash, digest_time, http_port, poll_min, queue_work, queue_interval_sec, schedule_poll_sec, updated_at
`

type UpdateAppSettingParams struct {
	EngineModeDefault string `json:"engine_mode_default"`
	AgentCliDefault   string `json:"agent_cli_default"`
	ConsoleTokenHash  string `json:"console_token_hash"`
	DigestTime        string `json:"digest_time"`
	HttpPort          int64  `json:"http_port"`
	PollMin           int64  `json:"poll_min"`
	QueueWork         int64  `json:"queue_work"`
	QueueIntervalSec  int64  `json:"queue_interval_sec"`
	SchedulePollSec   int64  `json:"schedule_poll_sec"`
	UpdatedAt         int64  `json:"updated_at"`
	ID                string `json:"id"`
}

func (q *Queries) UpdateAppSetting(ctx context.Context, arg UpdateAppSettingParams) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, updateAppSetting,
		arg.EngineModeDefault,
		arg.AgentCliDefault,
		arg.ConsoleTokenHash,
		arg.DigestTime,
		arg.HttpPort,
		arg.PollMin,
		arg.QueueWork,
		arg.QueueIntervalSec,
		arg.SchedulePollSec,
		arg.UpdatedAt,
		arg.ID,
	)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.EngineModeDefault,
		&i.AgentCliDefault,
		&i.ConsoleTokenHash,
		&i.DigestTime,
		&i.HttpPort,
		&i.PollMin,
		&i.QueueWork,
		&i.QueueIntervalSec,
		&i.SchedulePollSec,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCompanySetting = `-- name: UpdateCompanySetting :one
UPDATE company_setting SET engine_mode = ?, agent_cli = ?, issue_source = ?, issue_fixture_path = ?, updated_at = ? WHERE company_id = ? RETURNING company_id, engine_mode, agent_cli, issue_source, issue_fixture_path, updated_at
`

type UpdateCompanySettingParams struct {
	EngineMode       sql.NullString `json:"engine_mode"`
	AgentCli         sql.NullString `json:"agent_cli"`
	IssueSource      sql.NullString `json:"issue_source"`
	IssueFixturePath sql.NullString `json:"issue_fixture_path"`
	UpdatedAt        int64          `json:"updated_at"`
	CompanyID        string         `json:"company_id"`
}

func (q *Queries) UpdateCompanySetting(ctx context.Context, arg UpdateCompanySettingParams) (CompanySetting, error) {
	row := q.db.QueryRowContext(ctx, updateCompanySetting,
		arg.EngineMode,
		arg.AgentCli,
		arg.IssueSource,
		arg.IssueFixturePath,
		arg.UpdatedAt,
		arg.CompanyID,
	)
	var i CompanySetting
	err := row.Scan(
		&i.CompanyID,
		&i.EngineMode,
		&i.AgentCli,
		&i.IssueSource,
		&i.IssueFixturePath,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectSecret = `-- name: UpdateProjectSecret :one
UPDATE project_secret SET cipher = ?, updated_at = ? WHERE project_id = ? AND id = ? RETURNING project_id, id, cipher, updated_at
`

type UpdateProjectSecretParams struct {
	Cipher    string `json:"cipher"`
	UpdatedAt int64  `json:"updated_at"`
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateProjectSecret(ctx context.Context, arg UpdateProjectSecretParams) (ProjectSecret, error) {
	row := q.db.QueryRowContext(ctx, updateProjectSecret,
		arg.Cipher,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ID,
	)
	var i ProjectSecret
	err := row.Scan(
		&i.ProjectID,
		&i.ID,
		&i.Cipher,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSecret = `-- name: UpdateSecret :one
UPDATE secret SET cipher = ?, updated_at = ? WHERE company_id = ? AND id = ? RETURNING company_id, id, cipher, updated_at
`

type UpdateSecretParams struct {
	Cipher    string `json:"cipher"`
	UpdatedAt int64  `json:"updated_at"`
	CompanyID string `json:"company_id"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error) {
	row := q.db.QueryRowContext(ctx, updateSecret,
		arg.Cipher,
		arg.UpdatedAt,
		arg.CompanyID,
		arg.ID,
	)
	var i Secret
	err := row.Scan(
		&i.CompanyID,
		&i.ID,
		&i.Cipher,
		&i.UpdatedAt,
	)
	return i, err
}
