// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package query

import (
	"context"
	"database/sql"
)

const approveTask = `-- name: ApproveTask :one
UPDATE task
SET qstatus = 'ready', status = 'pending',
    lease_worker_id = '', lease_until = 0, last_error = '', updated_at = ?
WHERE id = ?
RETURNING id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at
`

type ApproveTaskParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ApproveTask(ctx context.Context, arg ApproveTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, approveTask, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CapabilityID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.ToolName,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.Risk,
		&i.Qstatus,
		&i.LeaseWorkerID,
		&i.LeaseUntil,
		&i.MaxAttempts,
		&i.TimeoutSec,
		&i.LastError,
		&i.Result,
		&i.WorkspacePath,
		&i.ParentTaskID,
		&i.RoundNo,
		&i.ConflictCount,
		&i.WriterEndpointID,
		&i.ReviewerEndpointID,
		&i.TestEndpointID,
		&i.ProjectID,
		&i.PipelineID,
		&i.PullRequestUrl,
		&i.PullRequestNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimTask = `-- name: ClaimTask :one
UPDATE task
SET qstatus = 'leased', lease_worker_id = ?, lease_until = ?, updated_at = ?
WHERE id = ? AND qstatus = 'ready'
RETURNING id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at
`

type ClaimTaskParams struct {
	LeaseWorkerID string `json:"lease_worker_id"`
	LeaseUntil    int64  `json:"lease_until"`
	UpdatedAt     int64  `json:"updated_at"`
	ID            string `json:"id"`
}

func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, claimTask,
		arg.LeaseWorkerID,
		arg.LeaseUntil,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CapabilityID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.ToolName,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.Risk,
		&i.Qstatus,
		&i.LeaseWorkerID,
		&i.LeaseUntil,
		&i.MaxAttempts,
		&i.TimeoutSec,
		&i.LastError,
		&i.Result,
		&i.WorkspacePath,
		&i.ParentTaskID,
		&i.RoundNo,
		&i.ConflictCount,
		&i.WriterEndpointID,
		&i.ReviewerEndpointID,
		&i.TestEndpointID,
		&i.ProjectID,
		&i.PipelineID,
		&i.PullRequestUrl,
		&i.PullRequestNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearTaskPipeline = `-- name: ClearTaskPipeline :execrows
UPDATE task SET pipeline_id = NULL WHERE pipeline_id = ?
`

func (q *Queries) ClearTaskPipeline(ctx context.Context, pipelineID sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearTaskPipeline, pipelineID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearTaskProject = `-- name: ClearTaskProject :execrows
UPDATE task SET project_id = NULL, pipeline_id = NULL WHERE project_id = ?
`

func (q *Queries) ClearTaskProject(ctx context.Context, projectID sql.NullString) (int64, error) {
	result, err := q.db.ExecContext(ctx, clearTaskProject, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeTask = `-- name: CompleteTask :one
UPDATE task SET qstatus = 'completed', status = 'completed', result = ?, updated_at = ? WHERE id = ? RETURNING id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at
`

type CompleteTaskParams struct {
	Result    string `json:"result"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, completeTask, arg.Result, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CapabilityID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.ToolName,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.Risk,
		&i.Qstatus,
		&i.LeaseWorkerID,
		&i.LeaseUntil,
		&i.MaxAttempts,
		&i.TimeoutSec,
		&i.LastError,
		&i.Result,
		&i.WorkspacePath,
		&i.ParentTaskID,
		&i.RoundNo,
		&i.ConflictCount,
		&i.WriterEndpointID,
		&i.ReviewerEndpointID,
		&i.TestEndpointID,
		&i.ProjectID,
		&i.PipelineID,
		&i.PullRequestUrl,
		&i.PullRequestNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countActiveTasksByProject = `-- name: CountActiveTasksByProject :one
SELECT COUNT(*) AS cnt FROM task
WHERE project_id = ? AND status IN ('pending', 'running', 'waiting_approval')
`

func (q *Queries) CountActiveTasksByProject(ctx context.Context, projectID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTasksByProject, projectID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO task (id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at
`

type CreateTaskParams struct {
	ID                 string         `json:"id"`
	CompanyID          string         `json:"company_id"`
	CapabilityID       sql.NullString `json:"capability_id"`
	WorkflowID         sql.NullString `json:"workflow_id"`
	AgentID            sql.NullString `json:"agent_id"`
	Title              string         `json:"title"`
	Description        string         `json:"description"`
	ToolName           string         `json:"tool_name"`
	Status             string         `json:"status"`
	Priority           int64          `json:"priority"`
	Attempt            int64          `json:"attempt"`
	Risk               string         `json:"risk"`
	Qstatus            string         `json:"qstatus"`
	LeaseWorkerID      string         `json:"lease_worker_id"`
	LeaseUntil         int64          `json:"lease_until"`
	MaxAttempts        int64          `json:"max_attempts"`
	TimeoutSec         int64          `json:"timeout_sec"`
	LastError          string         `json:"last_error"`
	Result             string         `json:"result"`
	WorkspacePath      string         `json:"workspace_path"`
	ParentTaskID       sql.NullString `json:"parent_task_id"`
	RoundNo            int64          `json:"round_no"`
	ConflictCount      int64          `json:"conflict_count"`
	WriterEndpointID   sql.NullString `json:"writer_endpoint_id"`
	ReviewerEndpointID sql.NullString `json:"reviewer_endpoint_id"`
	TestEndpointID     sql.NullString `json:"test_endpoint_id"`
	ProjectID          sql.NullString `json:"project_id"`
	PipelineID         sql.NullString `json:"pipeline_id"`
	CreatedAt          int64          `json:"created_at"`
	UpdatedAt          int64          `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.CompanyID,
		arg.CapabilityID,
		arg.WorkflowID,
		arg.AgentID,
		arg.Title,
		arg.Description,
		arg.ToolName,
		arg.Status,
		arg.Priority,
		arg.Attempt,
		arg.Risk,
		arg.Qstatus,
		arg.LeaseWorkerID,
		arg.LeaseUntil,
		arg.MaxAttempts,
		arg.TimeoutSec,
		arg.LastError,
		arg.Result,
		arg.WorkspacePath,
		arg.ParentTaskID,
		arg.RoundNo,
		arg.ConflictCount,
		arg.WriterEndpointID,
		arg.ReviewerEndpointID,
		arg.TestEndpointID,
		arg.ProjectID,
		arg.PipelineID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CapabilityID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.ToolName,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.Risk,
		&i.Qstatus,
		&i.LeaseWorkerID,
		&i.LeaseUntil,
		&i.MaxAttempts,
		&i.TimeoutSec,
		&i.LastError,
		&i.Result,
		&i.WorkspacePath,
		&i.ParentTaskID,
		&i.RoundNo,
		&i.ConflictCount,
		&i.WriterEndpointID,
		&i.ReviewerEndpointID,
		&i.TestEndpointID,
		&i.ProjectID,
		&i.PipelineID,
		&i.PullRequestUrl,
		&i.PullRequestNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failTask = `-- name: FailTask :one
UPDATE task SET qstatus = 'failed', status = 'failed', last_error = ?, updated_at = ? WHERE id = ? RETURNING id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at
`

type FailTaskParams struct {
	LastError string `json:"last_error"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, failTask, arg.LastError, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CapabilityID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.ToolName,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.Risk,
		&i.Qstatus,
		&i.LeaseWorkerID,
		&i.LeaseUntil,
		&i.MaxAttempts,
		&i.TimeoutSec,
		&i.LastError,
		&i.Result,
		&i.WorkspacePath,
		&i.ParentTaskID,
		&i.RoundNo,
		&i.ConflictCount,
		&i.WriterEndpointID,
		&i.ReviewerEndpointID,
		&i.TestEndpointID,
		&i.ProjectID,
		&i.PipelineID,
		&i.PullRequestUrl,
		&i.PullRequestNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at FROM task WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CapabilityID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.ToolName,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.Risk,
		&i.Qstatus,
		&i.LeaseWorkerID,
		&i.LeaseUntil,
		&i.MaxAttempts,
		&i.TimeoutSec,
		&i.LastError,
		&i.Result,
		&i.WorkspacePath,
		&i.ParentTaskID,
		&i.RoundNo,
		&i.ConflictCount,
		&i.WriterEndpointID,
		&i.ReviewerEndpointID,
		&i.TestEndpointID,
		&i.ProjectID,
		&i.PipelineID,
		&i.PullRequestUrl,
		&i.PullRequestNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const leaseNextTask = `-- name: LeaseNextTask :one
UPDATE task
SET qstatus = 'leased', lease_worker_id = ?, lease_until = ?, updated_at = ?
WHERE id = (SELECT id FROM task WHERE qstatus = 'ready' ORDER BY priority DESC, created_at ASC LIMIT 1)
RETURNING id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at
`

type LeaseNextTaskParams struct {
	LeaseWorkerID string `json:"lease_worker_id"`
	LeaseUntil    int64  `json:"lease_until"`
	UpdatedAt     int64  `json:"updated_at"`
}

func (q *Queries) LeaseNextTask(ctx context.Context, arg LeaseNextTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, leaseNextTask, arg.LeaseWorkerID, arg.LeaseUntil, arg.UpdatedAt)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CapabilityID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.ToolName,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.Risk,
		&i.Qstatus,
		&i.LeaseWorkerID,
		&i.LeaseUntil,
		&i.MaxAttempts,
		&i.TimeoutSec,
		&i.LastError,
		&i.Result,
		&i.WorkspacePath,
		&i.ParentTaskID,
		&i.RoundNo,
		&i.ConflictCount,
		&i.WriterEndpointID,
		&i.ReviewerEndpointID,
		&i.TestEndpointID,
		&i.ProjectID,
		&i.PipelineID,
		&i.PullRequestUrl,
		&i.PullRequestNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentTasks = `-- name: ListRecentTasks :many
SELECT id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at FROM task
WHERE company_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListRecentTasksParams struct {
	CompanyID string `json:"company_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListRecentTasks(ctx context.Context, arg ListRecentTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listRecentTasks, arg.CompanyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CapabilityID,
			&i.WorkflowID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.ToolName,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.Risk,
			&i.Qstatus,
			&i.LeaseWorkerID,
			&i.LeaseUntil,
			&i.MaxAttempts,
			&i.TimeoutSec,
			&i.LastError,
			&i.Result,
			&i.WorkspacePath,
			&i.ParentTaskID,
			&i.RoundNo,
			&i.ConflictCount,
			&i.WriterEndpointID,
			&i.ReviewerEndpointID,
			&i.TestEndpointID,
			&i.ProjectID,
			&i.PipelineID,
			&i.PullRequestUrl,
			&i.PullRequestNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at FROM task
WHERE (?1 = '' OR company_id = ?2)
  AND (?3 = '' OR status = ?4)
  AND (?5 = '' OR risk = ?6)
  AND (?7 = -1 OR attempt >= ?7)
ORDER BY created_at
`

type ListTasksParams struct {
	CompanyFilter interface{} `json:"company_filter"`
	CompanyID     string      `json:"company_id"`
	StatusFilter  interface{} `json:"status_filter"`
	Status        string      `json:"status"`
	RiskFilter    interface{} `json:"risk_filter"`
	Risk          string      `json:"risk"`
	AttemptFilter interface{} `json:"attempt_filter"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.CompanyFilter,
		arg.CompanyID,
		arg.StatusFilter,
		arg.Status,
		arg.RiskFilter,
		arg.Risk,
		arg.AttemptFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CapabilityID,
			&i.WorkflowID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.ToolName,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.Risk,
			&i.Qstatus,
			&i.LeaseWorkerID,
			&i.LeaseUntil,
			&i.MaxAttempts,
			&i.TimeoutSec,
			&i.LastError,
			&i.Result,
			&i.WorkspacePath,
			&i.ParentTaskID,
			&i.RoundNo,
			&i.ConflictCount,
			&i.WriterEndpointID,
			&i.ReviewerEndpointID,
			&i.TestEndpointID,
			&i.ProjectID,
			&i.PipelineID,
			&i.PullRequestUrl,
			&i.PullRequestNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByParent = `-- name: ListTasksByParent :many
SELECT id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at FROM task WHERE parent_task_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListTasksByParent(ctx context.Context, parentTaskID sql.NullString) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByParent, parentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CapabilityID,
			&i.WorkflowID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.ToolName,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.Risk,
			&i.Qstatus,
			&i.LeaseWorkerID,
			&i.LeaseUntil,
			&i.MaxAttempts,
			&i.TimeoutSec,
			&i.LastError,
			&i.Result,
			&i.WorkspacePath,
			&i.ParentTaskID,
			&i.RoundNo,
			&i.ConflictCount,
			&i.WriterEndpointID,
			&i.ReviewerEndpointID,
			&i.TestEndpointID,
			&i.ProjectID,
			&i.PipelineID,
			&i.PullRequestUrl,
			&i.PullRequestNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at FROM task
WHERE project_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListTasksByProjectParams struct {
	ProjectID sql.NullString `json:"project_id"`
	Limit     int64          `json:"limit"`
}

func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CapabilityID,
			&i.WorkflowID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.ToolName,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.Risk,
			&i.Qstatus,
			&i.LeaseWorkerID,
			&i.LeaseUntil,
			&i.MaxAttempts,
			&i.TimeoutSec,
			&i.LastError,
			&i.Result,
			&i.WorkspacePath,
			&i.ParentTaskID,
			&i.RoundNo,
			&i.ConflictCount,
			&i.WriterEndpointID,
			&i.ReviewerEndpointID,
			&i.TestEndpointID,
			&i.ProjectID,
			&i.PipelineID,
			&i.PullRequestUrl,
			&i.PullRequestNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskRunning = `-- name: MarkTaskRunning :one
UPDATE task SET qstatus = 'running', status = 'running', updated_at = ? WHERE id = ? RETURNING id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at
`

type MarkTaskRunningParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) MarkTaskRunning(ctx context.Context, arg MarkTaskRunningParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, markTaskRunning, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CapabilityID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.ToolName,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.Risk,
		&i.Qstatus,
		&i.LeaseWorkerID,
		&i.LeaseUntil,
		&i.MaxAttempts,
		&i.TimeoutSec,
		&i.LastError,
		&i.Result,
		&i.WorkspacePath,
		&i.ParentTaskID,
		&i.RoundNo,
		&i.ConflictCount,
		&i.WriterEndpointID,
		&i.ReviewerEndpointID,
		&i.TestEndpointID,
		&i.ProjectID,
		&i.PipelineID,
		&i.PullRequestUrl,
		&i.PullRequestNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recoverLeasedTasks = `-- name: RecoverLeasedTasks :many
UPDATE task
SET qstatus = 'ready', status = 'pending', lease_worker_id = '', lease_until = 0, updated_at = ?
WHERE qstatus = 'leased' AND lease_until != 0 AND lease_until < ?
RETURNING id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at
`

type RecoverLeasedTasksParams struct {
	UpdatedAt  int64 `json:"updated_at"`
	LeaseUntil int64 `json:"lease_until"`
}

func (q *Queries) RecoverLeasedTasks(ctx context.Context, arg RecoverLeasedTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, recoverLeasedTasks, arg.UpdatedAt, arg.LeaseUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CapabilityID,
			&i.WorkflowID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.ToolName,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.Risk,
			&i.Qstatus,
			&i.LeaseWorkerID,
			&i.LeaseUntil,
			&i.MaxAttempts,
			&i.TimeoutSec,
			&i.LastError,
			&i.Result,
			&i.WorkspacePath,
			&i.ParentTaskID,
			&i.RoundNo,
			&i.ConflictCount,
			&i.WriterEndpointID,
			&i.ReviewerEndpointID,
			&i.TestEndpointID,
			&i.ProjectID,
			&i.PipelineID,
			&i.PullRequestUrl,
			&i.PullRequestNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestApprovalTask = `-- name: RequestApprovalTask :one
UPDATE task
SET qstatus = 'waiting_approval', status = 'waiting_approval',
    lease_worker_id = '', lease_until = 0, updated_at = ?
WHERE id = ?
RETURNING id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at
`

type RequestApprovalTaskParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) RequestApprovalTask(ctx context.Context, arg RequestApprovalTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, requestApprovalTask, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CapabilityID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.ToolName,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.Risk,
		&i.Qstatus,
		&i.LeaseWorkerID,
		&i.LeaseUntil,
		&i.MaxAttempts,
		&i.TimeoutSec,
		&i.LastError,
		&i.Result,
		&i.WorkspacePath,
		&i.ParentTaskID,
		&i.RoundNo,
		&i.ConflictCount,
		&i.WriterEndpointID,
		&i.ReviewerEndpointID,
		&i.TestEndpointID,
		&i.ProjectID,
		&i.PipelineID,
		&i.PullRequestUrl,
		&i.PullRequestNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueTask = `-- name: RequeueTask :one
UPDATE task
SET qstatus = 'ready', status = 'pending', attempt = attempt + 1,
    lease_worker_id = '', lease_until = 0, last_error = ?, updated_at = ?
WHERE id = ?
RETURNING id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at
`

type RequeueTaskParams struct {
	LastError string `json:"last_error"`
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) RequeueTask(ctx context.Context, arg RequeueTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, requeueTask, arg.LastError, arg.UpdatedAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CapabilityID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.ToolName,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.Risk,
		&i.Qstatus,
		&i.LeaseWorkerID,
		&i.LeaseUntil,
		&i.MaxAttempts,
		&i.TimeoutSec,
		&i.LastError,
		&i.Result,
		&i.WorkspacePath,
		&i.ParentTaskID,
		&i.RoundNo,
		&i.ConflictCount,
		&i.WriterEndpointID,
		&i.ReviewerEndpointID,
		&i.TestEndpointID,
		&i.ProjectID,
		&i.PipelineID,
		&i.PullRequestUrl,
		&i.PullRequestNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTaskPullRequest = `-- name: SetTaskPullRequest :execrows
UPDATE task SET pull_request_url = ?, pull_request_number = ?, updated_at = ? WHERE id = ?
`

type SetTaskPullRequestParams struct {
	PullRequestUrl    sql.NullString `json:"pull_request_url"`
	PullRequestNumber sql.NullInt64  `json:"pull_request_number"`
	UpdatedAt         int64          `json:"updated_at"`
	ID                string         `json:"id"`
}

func (q *Queries) SetTaskPullRequest(ctx context.Context, arg SetTaskPullRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTaskPullRequest,
		arg.PullRequestUrl,
		arg.PullRequestNumber,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const taskStatusCountsByWorkflow = `-- name: TaskStatusCountsByWorkflow :many
SELECT workflow_id, status, COUNT(*) AS cnt
FROM task
WHERE company_id = ? AND workflow_id IS NOT NULL
GROUP BY workflow_id, status
ORDER BY workflow_id
`

type TaskStatusCountsByWorkflowRow struct {
	WorkflowID sql.NullString `json:"workflow_id"`
	Status     string         `json:"status"`
	Cnt        int64          `json:"cnt"`
}

func (q *Queries) TaskStatusCountsByWorkflow(ctx context.Context, companyID string) ([]TaskStatusCountsByWorkflowRow, error) {
	rows, err := q.db.QueryContext(ctx, taskStatusCountsByWorkflow, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskStatusCountsByWorkflowRow{}
	for rows.Next() {
		var i TaskStatusCountsByWorkflowRow
		if err := rows.Scan(&i.WorkflowID, &i.Status, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskRound = `-- name: UpdateTaskRound :one
UPDATE task
SET round_no = ?, conflict_count = ?, updated_at = ?
WHERE id = ?
RETURNING id, company_id, capability_id, workflow_id, agent_id, title, description, tool_name, status, priority, attempt, risk, qstatus, lease_worker_id, lease_until, max_attempts, timeout_sec, last_error, result, workspace_path, parent_task_id, round_no, conflict_count, writer_endpoint_id, reviewer_endpoint_id, test_endpoint_id, project_id, pipeline_id, pull_request_url, pull_request_number, created_at, updated_at
`

type UpdateTaskRoundParams struct {
	RoundNo       int64  `json:"round_no"`
	ConflictCount int64  `json:"conflict_count"`
	UpdatedAt     int64  `json:"updated_at"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateTaskRound(ctx context.Context, arg UpdateTaskRoundParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskRound,
		arg.RoundNo,
		arg.ConflictCount,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CapabilityID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.ToolName,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.Risk,
		&i.Qstatus,
		&i.LeaseWorkerID,
		&i.LeaseUntil,
		&i.MaxAttempts,
		&i.TimeoutSec,
		&i.LastError,
		&i.Result,
		&i.WorkspacePath,
		&i.ParentTaskID,
		&i.RoundNo,
		&i.ConflictCount,
		&i.WriterEndpointID,
		&i.ReviewerEndpointID,
		&i.TestEndpointID,
		&i.ProjectID,
		&i.PipelineID,
		&i.PullRequestUrl,
		&i.PullRequestNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
