// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package query

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO task (id, company_id, capability_id, workflow_id, agent_id, title, description, status, priority, attempt, risk, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, company_id, capability_id, workflow_id, agent_id, title, description, status, priority, attempt, risk, created_at, updated_at
`

type CreateTaskParams struct {
	ID           string         `json:"id"`
	CompanyID    string         `json:"company_id"`
	CapabilityID sql.NullString `json:"capability_id"`
	WorkflowID   sql.NullString `json:"workflow_id"`
	AgentID      sql.NullString `json:"agent_id"`
	Title        string         `json:"title"`
	Description  string         `json:"description"`
	Status       string         `json:"status"`
	Priority     int64          `json:"priority"`
	Attempt      int64          `json:"attempt"`
	Risk         string         `json:"risk"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.CompanyID,
		arg.CapabilityID,
		arg.WorkflowID,
		arg.AgentID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Attempt,
		arg.Risk,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CapabilityID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.Risk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, company_id, capability_id, workflow_id, agent_id, title, description, status, priority, attempt, risk, created_at, updated_at FROM task WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CapabilityID,
		&i.WorkflowID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Attempt,
		&i.Risk,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, company_id, capability_id, workflow_id, agent_id, title, description, status, priority, attempt, risk, created_at, updated_at FROM task
WHERE (?1 = '' OR company_id = ?2)
  AND (?3 = '' OR status = ?4)
ORDER BY created_at
`

type ListTasksParams struct {
	CompanyFilter interface{} `json:"company_filter"`
	CompanyID     string      `json:"company_id"`
	StatusFilter  interface{} `json:"status_filter"`
	Status        string      `json:"status"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.CompanyFilter,
		arg.CompanyID,
		arg.StatusFilter,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CapabilityID,
			&i.WorkflowID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Attempt,
			&i.Risk,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
