// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package query

import (
	"context"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflow (id, company_id, name, description, definition, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, company_id, name, description, definition, created_at, updated_at
`

type CreateWorkflowParams struct {
	ID          string `json:"id"`
	CompanyID   string `json:"company_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Definition  string `json:"definition"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, createWorkflow,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.Definition,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, company_id, name, description, definition, created_at, updated_at FROM workflow WHERE id = ?
`

func (q *Queries) GetWorkflow(ctx context.Context, id string) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflowsByCompany = `-- name: ListWorkflowsByCompany :many
SELECT id, company_id, name, description, definition, created_at, updated_at FROM workflow WHERE company_id = ? ORDER BY created_at
`

func (q *Queries) ListWorkflowsByCompany(ctx context.Context, companyID string) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkflowsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.Definition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
