DROP TABLE IF EXISTS audit;
DROP TABLE IF EXISTS task;
DROP TABLE IF EXISTS workflow;
DROP TABLE IF EXISTS permission;
DROP TABLE IF EXISTS policy;
DROP TABLE IF EXISTS agent;
DROP TABLE IF EXISTS capability;
DROP TABLE IF EXISTS company;
